name: skyfeed
description: Real-time app for Bluesky with a powerful Feed Builder
publish_to: 'none'
version: 0.9.5+95

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  atproto: ^0.6.9
  bluesky: ^0.8.24
  advanced_text_widgets:
    path: ../advanced_text_widgets
  hive: ^2.2.3
  path_provider: ^2.0.14
  filesize:
    git: https://github.com/redsolver/filesize.git
  unicons: ^2.1.1
  url_launcher: ^6.1.10
  web_socket_channel: ^2.4.0
  pasteboard: ^0.2.0
  elegant_notification: ^1.9.1
  flutter_svg: ^2.0.5
  rich_text_controller: ^1.4.2
  pool: ^1.5.1
  lib5: ^0.1.0
  s5_msgpack: ^0.3.0
  reorderables: ^0.6.0
  toggle_switch: ^2.1.0
  flutter_code_editor: ^0.3.0
  file_picker: ^5.3.2
  characters: ^1.3.0
  fuzzywuzzy: ^1.1.6
  any_syntax_highlighter: ^0.0.13
  fl_chart: ^0.63.0
  google_mlkit_translation: ^0.8.0
  google_mlkit_language_id: ^0.8.0
  # simple_icons: ^7.10.0
  exif: ^3.1.4
  stream_transform: ^2.1.0
  cbor: ^6.1.1
  thirds: ^0.2.0-alpha.1
  base_codecs: ^1.0.1

dependency_overrides:
  http: 1.0.0
  collection: 1.17.2
  extended_text: 11.1.0
  bluesky:
    path: ../atproto.dart/packages/bluesky
  extended_text_library: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/img/